import Head from "next/head";
import { Inter } from "next/font/google";

import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { MdOutlineKeyboardArrowRight } from "react-icons/md";

import Image from "next/image";
import deved from "../public/portada.png";

import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import exoOtaku from "../public/exootaku.png";
import exoOtakuDark from "../public/exootakusinfondo.png";
import raes from "../public/raes.png";

import html from "../assests/icons8-html-5-is-a-software-solution-stack-that-defines-the-properties-and-behaviors-of-web-page-96.png";
import css from "../assests/icons8-css3-96.png";
import js from "../assests/icons8-javascript-96.png";
import react from "../assests/icons8-react-a-javascript-library-for-building-user-interfaces-96.png";
import redux from "../assests/icons8-redux-96.png";
import mysql from "../assests/icons8-logo-de-mysql-96.png";
import mui from "../assests/icons8-material-ui-96.png";
import cui from "../assests/icons8-chakra-ui-96.png";
import tw from "../assests/icons8-tailwind-css-96.png";
import next from "../assests/1200px-Nextjs-logo.svg.png";
import express from "../assests/express.webp";
import node from "../assests/icons8-nodejs-96.png";
import postgress from "../assests/icons8-postgresql-96.png";
import ts from "../assests/icons8-typescript-96.png";

import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const techs = [
  {
    id: 1,
    src: html,
    title: "HTML",
    style: "shadow-blue-700 dark:shadow-orange-500",
  },
  {
    id: 2,
    src: css,
    title: "CSS",
    style: "shadow-blue-700",
  },
  {
    id: 3,
    src: js,
    title: "javascript",
    style: "shadow-blue-700",
  },
  {
    id: 4,
    src: react,
    title: "react",
    style: "shadow-blue-700",
  },
  {
    id: 5,
    src: redux,
    title: "redux",
    style: "shadow-blue-700",
  },
  {
    id: 6,
    src: mysql,
    title: "mysql",
    style: "shadow-blue-700",
  },
  {
    id: 7,
    src: mui,
    title: "materialui",
    style: "shadow-blue-700",
  },
  {
    id: 8,
    src: cui,
    title: "chakraui",
    style: "shadow-blue-700",
  },
  {
    id: 9,
    src: tw,
    title: "tailwild",
    style: "shadow-blue-700",
  },
  {
    id: 10,
    src: next,
    title: "nextjs",
    style: "shadow-blue-700",
  },
  {
    id: 11,
    src: express,
    title: "express",
    style: "shadow-blue-700",
  },
  {
    id: 12,
    src: node,
    title: "nodejs",
    style: "shadow-blue-700",
  },
  {
    id: 13,
    src: postgress,
    title: "postgress",
    style: "shadow-blue-700",
  },
  {
    id: 14,
    src: ts,
    title: "typescript",
    style: "shadow-blue-700",
  },
];

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Facundo Zanandrea Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-teal-100 px-10 md:px-20 dark:bg-gray-900">
        <section className="mb-10">
          <div className="grid sm:grid-cols-1 md:grid-cols-2 dark:text-white">
            <div className="flex justify-center m-5 md:m-10">
              <h1 className="text-5xl font-burtons dark:text-white">
                developed by Piki
              </h1>
            </div>
            <div className="flex items-center justify-center m-5 md:m-10">
              <div className="flex items-center justify-center">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </div>
              <div>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="../public/"
                  download="cv.pdf"
                >
                  Resume
                </a>
              </div>
            </div>
          </div>
          <div className="lg:grid lg:grid-cols-3 lg:justify-center lg:items-center xs:flex xs:flex-col">
            <div className="flex flex-col text-3xl gap-8 py-3 text-gray-600">
              <Link href={""}>
                <AiFillTwitterCircle className="cursor-pointer" />
              </Link>
              <Link
                href={
                  "https://www.linkedin.com/in/facundo-zanandrea-884958247/"
                }
                target="_blank"
              >
                <AiFillLinkedin className="cursor-pointer" />
              </Link>
              <Link href={"https://github.com/Facuzanan88/"} target="_blank">
                <AiFillGithub className="cursor-pointer" />
              </Link>
            </div>

            <div className="text-center p-10">
              <h2 className="text-3xl py-2 text-teal-600 font-medium md:text-6xl justify-center">
                Hola a Todos!
              </h2>
              <h3 className="text-2xl text-gray-800 md:text-xl">
                Mi nombre es{" "}
                <span className="text-teal-500"> Facundo Zanandrea</span> y soy{" "}
                <span className="text-teal-500">
                  {" "}
                  Desarrollador Web Full Stack
                </span>
              </h3>
              <div className="flex justify-center items-center">
                <Link
                  href="#contactame"
                  className="group text-white w-fit px-6 py-3 my-2 
                        flex items-center rounded-md bg-gradient-to-r
                        from-cyan-500 to-blue-500 cursor-pointer"
                >
                  Portfolio
                  <span className="group-hover:rotate-90 duration-300">
                    <MdOutlineKeyboardArrowRight size={25} className="ml-1" />
                  </span>
                </Link>
              </div>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 y-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image
                className="items-center"
                src={deved}
                alt={""}
                width={100}
                height={100}
                /* layout="fill"
              objectFit="cover" */
              />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Sobre mi</h3>
          </div>
        </section>
        <p className="text-md py-2 leading-8 text-gray-800">
          Since the beginning of my journey as a freelance designer and
          developer, I ve done remote work for
          <span className="text-teal-500"> agencies</span>
          consulted for <span className="text-teal-500"> startups</span>
          and collaborated with talanted people to create digital products for
          both business and consumer use.
        </p>
        <p className="text-md py-2 leading-8 text-gray-800">
          I offer from a wide range of services, including brand desing,
          programming and teaching.
        </p>
        <section>
          <div>
            <h3 className="text-3xl py-1">Mis Proyectos</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I ve done remote work for
              <span className="text-teal-500"> agencies</span>
              consulted for <span className="text-teal-500"> startups</span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand desing,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:grid first-letter lg:grid-cols-3 lg:gap-5 md:grid md:grid-cols-1">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gradient-to-b from-gray-700 to-gray-400">
              <Image
                src={darkMode ? exoOtakuDark : exoOtaku}
                alt={""}
                width={200}
                height={200}
                className="to-black"
              />
              <h3 className="text-lg font-medium ">E-Commerce Exo-Otaku</h3>
              <p className="py-1">
                Desarrollo de un SPA para una tienda de ropa donde puedes
                acceder como invitado, comprador o administrador. Incluye
                registro y gestión de inicio de sesión a través de Auth0, Stripe
                como pasarela de pago, carrito de compras, historial de
                transacciones y lista de deseos.
              </p>
              <h4 className="m- text-teal-600"> Tools </h4>
              <p className="text-gray-800 ">React / Redux</p>
              <p className="text-gray-800">MaterialUI / Auth0 / Cloudinary</p>
              <p className="text-gray-800 ">React / Node</p>
              <p className="text-gray-800 ">Sequelize / PostgreSQL</p>

              <div className="lg:flex lg:flex-row py-5 gap-10 md:justify-center md:flex-col">
                <div className="mb-8">
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md">
                    GitHub
                  </a>
                </div>
                <div>
                  <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md "
                    href="#"
                  >
                    Demo
                  </a>
                </div>
              </div>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gradient-to-b from-gray-700 to-gray-400">
              <Image
                src={darkMode ? exoOtakuDark : exoOtaku}
                alt={""}
                width={200}
                height={200}
                className="to-black"
              />
              <h3 className="text-lg font-medium ">E-Commerce Exo-Otaku</h3>
              <p className="py-1">
                Desarrollo de un SPA para una tienda de ropa donde puedes
                acceder como invitado, comprador o administrador. Incluye
                registro y gestión de inicio de sesión a través de Auth0, Stripe
                como pasarela de pago, carrito de compras, historial de
                transacciones y lista de deseos.
              </p>
              <h4 className="m- text-teal-600"> Tools </h4>
              <p className="text-gray-800 ">React / Redux</p>
              <p className="text-gray-800">MaterialUI / Auth0 / Cloudinary</p>
              <p className="text-gray-800 ">React / Node</p>
              <p className="text-gray-800 ">Sequelize / PostgreSQL</p>

              <div className="lg:flex lg:flex-row py-5 gap-10 md:justify-center md:flex-col">
                <div className="mb-8">
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md">
                    GitHub
                  </a>
                </div>
                <div>
                  <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md "
                    href="#"
                  >
                    Demo
                  </a>
                </div>
              </div>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-gradient-to-b from-gray-700 to-gray-400">
              <Image
                src={darkMode ? exoOtakuDark : exoOtaku}
                alt={""}
                width={200}
                height={200}
                className="to-black"
              />
              <h3 className="text-lg font-medium ">E-Commerce Exo-Otaku</h3>
              <p className="py-1">
                Desarrollo de un SPA para una tienda de ropa donde puedes
                acceder como invitado, comprador o administrador. Incluye
                registro y gestión de inicio de sesión a través de Auth0, Stripe
                como pasarela de pago, carrito de compras, historial de
                transacciones y lista de deseos.
              </p>
              <h4 className="m- text-teal-600"> Tools </h4>
              <p className="text-gray-800 ">React / Redux</p>
              <p className="text-gray-800">MaterialUI / Auth0 / Cloudinary</p>
              <p className="text-gray-800 ">React / Node</p>
              <p className="text-gray-800 ">Sequelize / PostgreSQL</p>

              <div className="lg:flex lg:flex-row py-5 gap-10 md:justify-center md:flex-col">
                <div className="mb-8">
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md">
                    GitHub
                  </a>
                </div>
                <div>
                  <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-20 py-2 rounded-md "
                    href="#"
                  >
                    Demo
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className=" w-full">
            {" "}
            {/* quito el h-screen que es el que me lo extiende por sobre las otras secciones */}
            <div className="max-w-screen-lg mx-auto p-4 flex flex-col justify-center w-full h-full">
              <div>
                <p className="text-4xl font-bold border-b-4 border-gray-500 p-2 inline">
                  Experience
                </p>
                <p className="py-6">
                  These are the technologies i`ve worked with
                </p>
              </div>

              <div className="lg:grid lg:grid-cols-3 gap-12 text-center py-8 px-10 sm:px-0 sm:flex sm:flex-col sm:py-10">
                {techs.map(({ id, src, title, style }) => (
                  // eslint-disable-next-line react/jsx-key
                  <div
                    key={id}
                    className={`shadow-md hover:scale-105 duration-500 py-2 rounded-lg ${style}`}
                  >
                    <picture>
                      <Image
                        src={src}
                        alt={"html"}
                        width={55}
                        height={55}
                        className="w-20 mx-auto mt-4"
                      />
                    </picture>
                    <p className="mt-4 font-burtons text-xl">{title}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="contact">
          <h3 className="text-3xl">Contactame!</h3>
          <div className="w-full h-screen flex justify-center items-center">
            <form
              action="https://getform.io/f/d1e99e59-27e8-4877-9d6b-cb6f66f66ae2"
              method="POST"
              className="flex flex-col w-full md:w-1/2 justify-center items-center"
            >
              <div>
                <label
                  className="block uppercase tracking-wide text-gray-700 dark:text-gray-400 text-xs font-bold mb-2"
                  htmlFor="grid-password"
                >
                  Nombre
                </label>
                <input
                  type="text"
                  name="name"
                  placeholder="Ingrese su nombre"
                  className="p-2 h-14 bg-transparent w-96 border-2 rounded-md text-white focus:outline-none"
                />
              </div>
              <div className="my-20">
                <label
                  className="block uppercase tracking-wide text-gray-700 dark:text-gray-400 text-xs font-bold mb-2"
                  htmlFor="grid-password"
                >
                  E-mail
                </label>
                <input
                  type="text"
                  name="email"
                  placeholder="Ingrese su email"
                  className=" h-14 p-2 bg-transparent w-96  border-2 rounded-md text-white focus:outline-none md:mx-5"
                />
              </div>
              <div>
                <label
                  className="block uppercase tracking-wide text-gray-700 dark:text-gray-400 text-xs font-bold mb-2 md:mx-5"
                  htmlFor="grid-password"
                >
                  Mensaje
                </label>
                <textarea
                  name="message"
                  placeholder="Ingrese su mensaje"
                  rows={10}
                  className="p-2 bg-transparent w-96  border-2 rounded-md text-white focus:outline-none"
                />
              </div>
              <button className="text-white bg-gradient-to-b from-cyan-500 to-blue-500 px-6 py-3 my-8 mx-auto flex items-center rounded-md hover:scale-110 duration-300">
                Enviar
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
