import Head from "next/head";
import { Inter } from "next/font/google";

import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

import code from "../public/code.png";
import consulting from "../public/consulting.png";
import desing from "../public/design.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facundo Zanandrea Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developed by Piki</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Facundo Zanandrea
            </h2>
            <h3 className="text-2xl py-2">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Freelancer providing services for programming and dessing content
              needs. Join me down below and lets get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 y-80 mt-20 overflow-hidden">
            <Image
              className="items-center h-64"
              src={deved}
              alt={""}
              /* layout="fill"
              objectFit="cover" */
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I ve done remote work for
              <span className="text-teal-500"> agencies</span>
              consulted for <span className="text-teal-500"> startups</span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand desing,
              programming and teaching.
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={desing} alt={""} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Desings
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs followings core
                desing thory.
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} alt={""} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Desings
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs followings core
                desing thory.
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} alt={""} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Desings
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs followings core
                desing thory.
              </p>
              <h4 className="py-4 text-teal-600">Desing tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section></section>
      </main>
    </div>
  );
}
